server:
  port: 8082

spring:
  application:
    name: ai-cloud
  
  # Spring AI Ollama 配置
  ai:
    ollama:
      base-url: http://35.221.238.240:11434
      chat:
        options:
          model: qwen2.5vl:3b
          temperature: 0.7

# SpringDoc OpenAPI 配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  info:
    title: AI Cloud 服务 API
    description: AI Cloud Ollama 调用服务接口文档
    version: 1.0.0
    contact:
      name: liangjunhui
      email: liangjunhui@example.com

